(()=>{
const cfg=window.BLN_CONFIG||{};const DEMO=cfg.DEMO_MODE||!cfg.SUPABASE_URL||!cfg.SUPABASE_ANON_KEY;const sb=!DEMO?window.supabase.createClient(cfg.SUPABASE_URL,cfg.SUPABASE_ANON_KEY):null;
const state={customers:[{id:'c1',name:'Nulaid'},{id:'c2',name:'Yosemite Foods'},{id:'c3',name:'Refresco'}],facilities:[{id:'f1',customer_id:'c1',name:'Ripon',city:'Ripon',state:'CA'},{id:'f2',customer_id:'c2',name:'Modesto',city:'Modesto',state:'CA'},{id:'f3',customer_id:'c3',name:'Modesto',city:'Modesto',state:'CA'}],equipment:[],reports:[],facilityId:'f1'};
const $=(s,r=document)=>r.querySelector(s),$$=(s,r=document)=>[...r.querySelectorAll(s)];
const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
const types={raw_water:'Raw Water',soft_water:'Soft Water',softener:'Water Softener',ro_water:'RO Water',feed_water:'Feed Water',feed_tank:'Feed Water Tank',boiler:'Boiler',cooling_tower:'Cooling Tower',other:'Other'};
function eq(id,f,t,n,c='permanent'){return{id,facility_id:f,type:t,name:n,equipment_class:c,status:'active'}}
state.equipment=[eq('e1','f1','raw_water','Raw Water'),eq('e2','f1','soft_water','Soft Water'),eq('e3','f1','boiler','Boiler #1'),eq('e4','f1','boiler','Rental Boiler #1','rental'),eq('e5','f1','cooling_tower','Cooling Tower #1'),eq('e6','f2','raw_water','Raw Water'),eq('e7','f2','feed_tank','Feed Tank'),eq('e8','f2','boiler','Boiler #1'),eq('e9','f3','soft_water','Soft Water'),eq('e10','f3','boiler','Boiler #1')];
state.reports=[{id:'r1',report_number:842,facility_id:'f1',service_date:'2026-09-10',status:'completed',program_status:'Stable'},{id:'r2',report_number:841,facility_id:'f2',service_date:'2026-09-09',status:'revised',program_status:'Watch'},{id:'r3',report_number:840,facility_id:'f3',service_date:'2026-09-08',status:'draft',program_status:null}];
function params(t){if(t==='boiler')return[['Raw Conductivity','raw_conductivity','none',null,null],['Neutralized Conductivity','neutralized_conductivity','range',2500,3000],['OH Alkalinity','oh_alkalinity','min',150,null],['pH','ph','min',10.8,null],['Phosphate','phosphate','range',35,50],['Sulfite','sulfite','range',30,60]];if(t==='cooling_tower')return[['Hardness','hardness','max',null,350],['Conductivity','conductivity','range',1200,1500],['pH','ph','range',7,9],['Phosphonate','phosphonate','range',8,12],['Biocide','biocide','none',null,null]];return[['pH','ph','none',null,null],['Conductivity','conductivity','none',null,null],['Hardness','hardness',t==='raw_water'?'none':'range',0,4],['Alkalinity','alkalinity','none',null,null]]}
function target(p){return p[2]==='range'?`${p[3]}–${p[4]}`:p[2]==='min'?`≥${p[3]}`:p[2]==='max'?`<${p[4]}`:'—'}
function classify(p,v){if(v===''||p[2]==='none')return'none';v=+v;if(p[2]==='range')return v>=p[3]&&v<=p[4]?'green':((v>=p[3]*.9&&v<p[3])||(v>p[4]&&v<=p[4]*1.1))?'yellow':'red';if(p[2]==='min')return v>=p[3]?'green':v>=p[3]*.9?'yellow':'red';if(p[2]==='max')return v<=p[4]?'green':v<=p[4]*1.1?'yellow':'red';return'none'}
function facility(id){return state.facilities.find(x=>x.id===id)}function customer(id){return state.customers.find(x=>x.id===id)}function icon(t){return t==='boiler'?'B':t==='cooling_tower'?'CT':'W'}
function rowReport(r){const f=facility(r.facility_id),c=customer(f.customer_id),cl=r.program_status==='Stable'?'green':r.program_status==='Watch'?'yellow':r.program_status?'red':'gray';return`<div class="rowcard"><div class="rowtop"><div><h4>${esc(c.name)} — ${esc(f.name)}</h4><div class="meta">${r.service_date} · Report #${r.report_number}</div></div><span class="badge ${cl}">${esc(r.program_status||r.status)}</span></div></div>`}
function render(){renderDashboard();renderCustomers();renderFacility();renderReports();populateReport()}
function renderDashboard(){$('#recentReports').innerHTML=state.reports.map(rowReport).join('');$('#recentEquipment').innerHTML=state.equipment.slice(-5).reverse().map(e=>`<div class="rowcard"><strong>${esc(e.name)}</strong><div class="meta">${esc(facility(e.facility_id).name)} · ${e.equipment_class}</div></div>`).join('')}
function renderCustomers(){const q=$('#customerSearch').value.toLowerCase();$('#customerList').innerHTML=state.customers.filter(c=>c.name.toLowerCase().includes(q)).map(c=>{const fs=state.facilities.filter(f=>f.customer_id===c.id),n=state.equipment.filter(e=>fs.some(f=>f.id===e.facility_id)).length;return`<div class="rowcard customer" data-id="${c.id}"><div class="rowtop"><div><h4>${esc(c.name)}</h4><div class="meta">${fs.length} facilit${fs.length===1?'y':'ies'} · ${n} active systems</div></div><span class="badge gray">Open</span></div></div>`}).join('');$$('.customer').forEach(x=>x.onclick=()=>{const f=state.facilities.find(z=>z.customer_id===x.dataset.id);if(f){state.facilityId=f.id;renderFacility();go('facility')}})}
function renderFacility(){const f=facility(state.facilityId),c=customer(f.customer_id);$('#facilityTitle').textContent=`${c.name} — ${f.name}`;const es=state.equipment.filter(e=>e.facility_id===f.id);$('#equipmentGrid').innerHTML=es.map(e=>`<div class="card equipment"><div class="eqtop"><div class="icon">${icon(e.type)}</div><span class="badge green">${e.equipment_class==='rental'?'Rental':'Active'}</span></div><h4>${esc(e.name)}</h4><div class="meta">${esc(types[e.type])} · ${e.equipment_class}</div><div class="targets">${params(e.type).filter(p=>p[2]!=='none').slice(0,3).map(p=>`<div class="target"><span>${esc(p[0])}</span><strong>${target(p)}</strong></div>`).join('')}</div></div>`).join('');$('#targetsList').innerHTML=es.map(e=>`<div class="rowcard"><h4>${esc(e.name)}</h4><div class="meta">${params(e.type).filter(p=>p[2]!=='none').map(p=>`${p[0]} ${target(p)}`).join(' · ')||'No scored targets'}</div></div>`).join('');$('#facilityReports').innerHTML=state.reports.filter(r=>r.facility_id===f.id).map(rowReport).join('')}
function renderReports(){$('#reportsList').innerHTML=state.reports.map(rowReport).join('')}
function populateReport(){$('#reportCustomer').innerHTML=state.customers.map(c=>`<option value="${c.id}">${esc(c.name)}</option>`).join('');populateFacilities()}
function populateFacilities(){const cid=$('#reportCustomer').value||state.customers[0].id;$('#reportFacility').innerHTML=state.facilities.filter(f=>f.customer_id===cid).map(f=>`<option value="${f.id}">${esc(f.name)}</option>`).join('');buildReport()}
function buildReport(){const fid=$('#reportFacility').value;$('#reportEquipment').innerHTML=state.equipment.filter(e=>e.facility_id===fid&&e.status==='active').map(e=>`<div class="system" data-eid="${e.id}"><div class="systemhead"><strong>${icon(e.type)} ${esc(e.name)}</strong><span>${e.equipment_class}</span></div><div class="systembody"><div class="readings">${params(e.type).map((p,i)=>`<div class="reading"><label>${esc(p[0])}${p[2]!=='none'?` · ${target(p)}`:''}</label><input inputmode="decimal" data-param='${esc(JSON.stringify(p))}'><span class="pill gray">Not scored</span></div>`).join('')}</div><label style="display:block;margin-top:12px;font-size:12px;font-weight:800;color:#4c5968">Notes<textarea rows="3"></textarea></label></div></div>`).join('');$$('#reportEquipment input').forEach(i=>i.oninput=updateSnapshot);updateSnapshot()}
function updateSnapshot(){let g=0,y=0,r=0,t=0;$$('#reportEquipment input[data-param]').forEach(i=>{const p=JSON.parse(i.dataset.param),s=classify(p,i.value),pill=i.nextElementSibling;pill.className='pill '+(s==='none'?'gray':s);pill.textContent=s==='green'?'In Range':s==='yellow'?'Slightly Out':s==='red'?'Out of Range':'Not scored';if(s!=='none'){t++;if(s==='green')g++;if(s==='yellow')y++;if(s==='red')r++}});$('#mTested').textContent=t;$('#mGreen').textContent=g;$('#mYellow').textContent=y;$('#mRed').textContent=r;let text='No Data',cl='neutral';if(t){if(r||y/t>.3){text='Needs Attention';cl='red'}else if(y){text='Watch';cl='yellow'}else{text='Stable';cl='green'}}$('#programStatus').textContent=text;$('#programStatus').className='program '+cl}
function go(id){$$('.route').forEach(x=>x.classList.remove('active'));$('#'+id).classList.add('active');$$('.nav').forEach(x=>x.classList.toggle('active',x.dataset.route===id));const names={'dashboard':['Dashboard','Service program overview'],'customers':['Customers','Customer and facility management'],'reports':['Service Reports','History, revisions, PDFs, and exports'],'new-report':['New Service Report','Field service entry'],'facility':['Facility Setup','Equipment, targets, reports, and trends']};$('#pageTitle').textContent=names[id][0];$('#pageSubtitle').textContent=names[id][1];scrollTo({top:0,behavior:'smooth'})}
function openModal(title,body){$('#modalTitle').textContent=title;$('#modalBody').innerHTML=body;$('#modal').classList.remove('hidden')}function closeModal(){$('#modal').classList.add('hidden')}function toast(s){$('#toast').textContent=s;$('#toast').classList.remove('hidden');setTimeout(()=>$('#toast').classList.add('hidden'),2500)}
function addEquipment(fromReport=false){const fid=fromReport?$('#reportFacility').value:state.facilityId;openModal('Add Equipment',`<div class="formgrid"><label>Equipment Type<select id="mType">${Object.entries(types).map(([v,n])=>`<option value="${v}">${n}</option>`).join('')}</select></label><label>Name / Tag<input id="mName" placeholder="e.g. Rental Boiler #2"></label><label>Equipment Class<select id="mClass"><option value="permanent">Permanent</option><option value="rental">Rental</option><option value="temporary">Temporary</option></select></label></div><div class="modalactions"><button class="btn" id="cancel">Cancel</button><button class="btn primary" id="saveEq">Add Equipment</button></div>`);$('#cancel').onclick=closeModal;$('#saveEq').onclick=async()=>{const n=$('#mName').value.trim();if(!n)return toast('Enter an equipment name.');if(DEMO){state.equipment.push(eq('e'+Date.now(),fid,$('#mType').value,n,$('#mClass').value));closeModal();renderFacility();if(fromReport)buildReport();toast('Equipment added.');return}try{const t=await sb.from('service_equipment_types').select('id').eq('code',$('#mType').value).single();if(t.error)throw t.error;const ins=await sb.from('service_facility_equipment').insert({facility_id:fid,equipment_type_id:t.data.id,name:n,equipment_class:$('#mClass').value,status:'active'});if(ins.error)throw ins.error;closeModal();toast('Equipment added.');await loadSupabase()}catch(e){toast(e.message)}}}
async function saveReport(status){const fid=$('#reportFacility').value,ps=$('#programStatus').textContent;const f=facility(fid),c=customer(f.customer_id);if(!fid)return toast('Choose a facility.');if(DEMO){const r={id:'r'+Date.now(),report_number:Math.max(...state.reports.map(x=>x.report_number))+1,facility_id:fid,service_date:$('#serviceDate').value,status,program_status:ps==='No Data'?null:ps};state.reports.unshift(r);render();if(status==='completed')makePDF(r,c,f);toast(status==='completed'?'Report completed.':'Draft saved.');return}toast('Supabase save is wired for the next pass after the test schema is connected.')}
function makePDF(r,c,f){const{jsPDF}=window.jspdf,doc=new jsPDF('p','pt','letter');doc.setFont('helvetica','bold');doc.setFontSize(18);doc.setTextColor(11,47,89);doc.text('B & L Neeley, Inc.',54,52);doc.setFontSize(10);doc.setTextColor(80);doc.text('Service Report - Water, Boiler & Cooling Systems',54,70);doc.setTextColor(20);doc.text(`Customer: ${c.name}`,54,100);doc.text(`Facility: ${f.name}`,320,100);doc.text(`Date: ${r.service_date}`,54,118);let y=150;$$('#reportEquipment .system').forEach(s=>{const e=state.equipment.find(x=>x.id===s.dataset.eid),rows=$$('input[data-param]',s).filter(i=>i.value!=='').map(i=>{const p=JSON.parse(i.dataset.param);return[p[0],i.value,p[2]==='none'?'—':target(p),i.nextElementSibling.textContent]});if(!rows.length)return;doc.setFont('helvetica','bold');doc.setTextColor(11,47,89);doc.text(e.name,54,y);doc.autoTable({startY:y+8,head:[['Parameter','Result','Target','Status']],body:rows,margin:{left:54,right:54},headStyles:{fillColor:[11,47,89]},styles:{fontSize:9}});y=doc.lastAutoTable.finalY+20;if(y>690){doc.addPage();y=50}});doc.save(`${c.name}_${f.name}_Report_${r.service_date}.pdf`)}
async function loadSupabase(){if(DEMO)return;const[c,f,e,r]=await Promise.all([sb.from('service_customers').select('*'),sb.from('service_facilities').select('*'),sb.from('service_facility_equipment').select('*,service_equipment_types(code,display_name)'),sb.from('service_reports').select('*').order('service_date',{ascending:false})]);if(c.error||f.error||e.error||r.error)return toast('Could not load Supabase data.');state.customers=c.data;state.facilities=f.data;state.equipment=e.data.map(x=>({id:x.id,facility_id:x.facility_id,type:x.service_equipment_types?.code||'other',name:x.name,equipment_class:x.equipment_class,status:x.status}));state.reports=r.data;state.facilityId=state.facilities[0]?.id;render()}
$$('[data-route]').forEach(x=>x.onclick=()=>go(x.dataset.route));$$('.tab').forEach(x=>x.onclick=()=>{$$('.tab').forEach(t=>t.classList.remove('active'));$$('.tabpane').forEach(t=>t.classList.remove('active'));x.classList.add('active');$('#'+x.dataset.tab).classList.add('active')});$('#customerSearch').oninput=renderCustomers;$('#reportCustomer').onchange=populateFacilities;$('#reportFacility').onchange=buildReport;$('#addEquipment').onclick=()=>addEquipment(false);$('#addEquipmentReport').onclick=()=>addEquipment(true);$('#closeModal').onclick=closeModal;$('#saveDraft').onclick=()=>saveReport('draft');$('#completeReport').onclick=()=>saveReport('completed');$('#addCustomer').onclick=()=>toast('Customer creation form is next in the admin pass.');$('#serviceDate').value=new Date().toISOString().slice(0,10);
if(DEMO)render();else loadSupabase();
})();
