(()=>{
const cfg=window.BLN_CONFIG||{};const DEMO=cfg.DEMO_MODE||!cfg.SUPABASE_URL||!cfg.SUPABASE_ANON_KEY;const sb=!DEMO?window.supabase.createClient(cfg.SUPABASE_URL,cfg.SUPABASE_ANON_KEY):null;
const state={user:null,profile:null,permissions:null,users:[],equipmentTypes:[],targets:[],customers:[],facilities:[],equipment:[],reports:[],facilityId:null};
const $=(s,r=document)=>r.querySelector(s),$$=(s,r=document)=>[...r.querySelectorAll(s)];
const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
const types={raw_water:'Raw Water',soft_water:'Soft Water',softener:'Water Softener',ro_water:'RO Water',feed_water:'Feed Water',feed_tank:'Feed Water Tank',boiler:'Boiler',cooling_tower:'Cooling Tower',closed_loop:'Closed Loop System',other:'Other'};
function fallbackParams(t){if(t==='boiler')return[['Raw Conductivity','raw_conductivity','none',null,null],['Neutralized Conductivity','neutralized_conductivity','range',2500,3000],['Alkalinity','alkalinity','min',400,null,'auto'],['OH Alkalinity','oh_alkalinity','min',150,null],['pH','ph','min',10.8,null],['Phosphate','phosphate','range',35,50],['Sulfite','sulfite','range',30,60]];if(t==='cooling_tower')return[['Hardness','hardness','max',null,350],['Conductivity','conductivity','range',1200,1500],['pH','ph','range',7,9],['Phosphonate','phosphonate','range',8,12],['Biocide','biocide','none',null,null]];return[['pH','ph','none',null,null],['Conductivity','conductivity','none',null,null],['Hardness','hardness',t==='raw_water'?'none':'range',0,4],['Alkalinity','alkalinity','none',null,null]]}
function paramsForEquipment(e){const rows=state.targets.filter(x=>x.facility_equipment_id===e.id&&x.active!==false).sort((a,b)=>(a.sort_order||0)-(b.sort_order||0));if(rows.length)return rows.map(x=>[x.parameter_name,x.parameter_code,x.target_type==='minimum'?'min':x.target_type==='maximum'?'max':x.target_type,x.target_min,x.target_max,x.input_type==='calculated'?'auto':null,x.warning_min,x.warning_max]);return fallbackParams(e.type)}
function target(p){return p[2]==='range'?`${p[3]}–${p[4]}`:p[2]==='min'?`≥${p[3]}`:p[2]==='max'?`<${p[4]}`:'—'}
function classify(p,v){if(v===''||p[2]==='none')return'none';v=+v;const wmin=p[6],wmax=p[7];if(p[2]==='range')return v>=p[3]&&v<=p[4]?'green':((wmin!=null&&v>=wmin&&v<p[3])||(wmax!=null&&v>p[4]&&v<=wmax))?'yellow':'red';if(p[2]==='min')return v>=p[3]?'green':wmin!=null&&v>=wmin?'yellow':'red';if(p[2]==='max')return v<=p[4]?'green':wmax!=null&&v<=wmax?'yellow':'red';return'none'}
function facility(id){return state.facilities.find(x=>x.id===id)}function customer(id){return state.customers.find(x=>x.id===id)}function icon(t){return t==='boiler'?'B':t==='cooling_tower'?'CT':t==='closed_loop'?'CL':'W'}
function equipmentSort(a,b){const ta=state.equipmentTypes.find(x=>x.code===a.type),tb=state.equipmentTypes.find(x=>x.code===b.type);return (ta?.sort_order??90)-(tb?.sort_order??90)||(a.sort_order??0)-(b.sort_order??0)||a.name.localeCompare(b.name)}
function rowReport(r){const f=facility(r.facility_id),c=customer(f.customer_id),cl=r.program_status==='Stable'?'green':r.program_status==='Watch'?'yellow':r.program_status?'red':'gray';return`<div class="rowcard"><div class="rowtop"><div><h4>${esc(c.name)} — ${esc(f.name)}</h4><div class="meta">${r.service_date} · Report #${r.report_number}</div></div><span class="badge ${cl}">${esc(r.program_status||r.status)}</span></div></div>`}
function render(){renderDashboard();renderCustomers();renderFacility();renderReports();populateReport();if(state.profile?.role==='admin')renderUsers()}
function renderDashboard(){const now=new Date(),month=now.toISOString().slice(0,7),monthReports=state.reports.filter(r=>String(r.service_date||'').startsWith(month)),completed=monthReports.filter(r=>r.status!=='draft'),stable=completed.filter(r=>r.program_status==='Stable');$('#kpiFacilities').textContent=state.facilities.length;$('#kpiReports').textContent=monthReports.length;$('#kpiStable').textContent=completed.length?Math.round(stable.length/completed.length*100)+'%':'—';$('#kpiDrafts').textContent=state.reports.filter(r=>r.status==='draft').length;$('#recentReports').innerHTML=state.reports.length?state.reports.slice(0,5).map(rowReport).join(''):'<div class="empty-state">No service reports yet.</div>';$('#recentEquipment').innerHTML=state.equipment.length?state.equipment.slice(-5).reverse().map(e=>`<div class="rowcard"><strong>${esc(e.name)}</strong><div class="meta">${esc(facility(e.facility_id)?.name||'')} · ${e.equipment_class}</div></div>`).join(''):'<div class="empty-state">No equipment has been added yet.</div>'}
function renderCustomers(){const q=$('#customerSearch').value.toLowerCase();const matches=state.customers.filter(c=>c.name.toLowerCase().includes(q)||state.facilities.some(f=>f.customer_id===c.id&&((f.name||'')+' '+(f.city||'')).toLowerCase().includes(q)));$('#customerList').innerHTML=matches.length?matches.map(c=>{const fs=state.facilities.filter(f=>f.customer_id===c.id),n=state.equipment.filter(e=>fs.some(f=>f.id===e.facility_id)).length;return`<div class="rowcard customer-block"><div class="rowtop"><div><h4>${esc(c.name)}</h4><div class="meta">${fs.length} facilit${fs.length===1?'y':'ies'} · ${n} active systems</div></div><button class="btn soft add-facility" data-cid="${c.id}">+ Facility</button></div><div class="facility-list">${fs.length?fs.map(f=>`<button class="facility-row" data-fid="${f.id}"><span><strong>${esc(f.name)}</strong><small>${esc([f.city,f.state].filter(Boolean).join(', ')||'No address entered')}</small></span><span>Open ›</span></button>`).join(''):'<div class="meta" style="padding-top:12px">No facilities yet.</div>'}</div></div>`}).join(''):'<div class="empty-state">No customers or facilities found.</div>';$$('.add-facility').forEach(x=>x.onclick=e=>{e.stopPropagation();openFacilityModal(x.dataset.cid)});$$('.facility-row').forEach(x=>x.onclick=()=>{state.facilityId=x.dataset.fid;renderFacility();go('facility')})}
function openFacilityModal(customerId,facilityId=null){if(state.profile?.role!=='admin'&&!state.permissions?.manage_facilities)return toast('Facility management access required.');const f=facilityId?facility(facilityId):null,c=customer(customerId);openModal(f?'Edit Facility':'Add Facility',`<div class="formgrid"><label>Customer<input value="${esc(c?.name||'')}" disabled></label><label>Facility Name<input id="mFacilityName" value="${esc(f?.name||'')}" placeholder="e.g. Modesto Plant"></label><label>Address<input id="mAddress1" value="${esc(f?.address1||'')}"></label><label>Address 2<input id="mAddress2" value="${esc(f?.address2||'')}"></label><label>City<input id="mCity" value="${esc(f?.city||'')}"></label><label>State<input id="mState" value="${esc(f?.state||'')}" maxlength="2"></label><label>ZIP<input id="mZip" value="${esc(f?.postal_code||'')}"></label><label style="grid-column:1/-1">Facility Notes<textarea id="mFacilityNotes" rows="3">${esc(f?.notes||'')}</textarea></label></div><div class="modalactions"><button class="btn" id="cancel">Cancel</button><button class="btn primary" id="saveFacility">${f?'Save Changes':'Add Facility'}</button></div>`);$('#cancel').onclick=closeModal;$('#saveFacility').onclick=async()=>{const name=$('#mFacilityName').value.trim();if(!name)return toast('Enter a facility name.');const vals={customer_id:customerId,name,address1:$('#mAddress1').value.trim()||null,address2:$('#mAddress2').value.trim()||null,city:$('#mCity').value.trim()||null,state:$('#mState').value.trim().toUpperCase()||null,postal_code:$('#mZip').value.trim()||null,notes:$('#mFacilityNotes').value.trim()||null,active:true};const q=f?await sb.from('facilities').update(vals).eq('id',f.id).select().single():await sb.from('facilities').insert(vals).select().single();if(q.error)return toast(q.error.message);state.facilityId=q.data.id;closeModal();await loadSupabase();go('facility');toast(f?'Facility updated.':'Facility added.')}}
function renderFacility(){const f=facility(state.facilityId);if(!f){$('#facilityTitle').textContent='Facility Setup';$('#facilityMeta').textContent='Add a customer and facility to begin.';$('#equipmentGrid').innerHTML='<div class="card empty"><h3>No facility selected</h3><p>Create your first customer and facility to configure equipment and targets.</p></div>';$('#targetsList').innerHTML='';$('#facilityReports').innerHTML='';return}const c=customer(f.customer_id);$('#facilityTitle').textContent=`${c.name} — ${f.name}`;$('#facilityMeta').innerHTML=`${esc([f.address1,f.city,f.state,f.postal_code].filter(Boolean).join(' · ')||'Facility equipment and program setup.')} <button class="link" id="editFacility">Edit Facility</button>`;$('#editFacility').onclick=()=>openFacilityModal(f.customer_id,f.id);const es=state.equipment.filter(e=>e.facility_id===f.id).sort(equipmentSort);$('#equipmentGrid').innerHTML=es.map(e=>`<div class="card equipment"><div class="eqtop"><div class="icon">${icon(e.type)}</div><span class="badge green">${e.equipment_class==='rental'?'Rental':'Active'}</span></div><h4>${esc(e.name)}</h4><div class="meta">${esc(types[e.type])} · ${e.equipment_class}</div><div class="targets">${paramsForEquipment(e).filter(p=>p[2]!=='none').slice(0,3).map(p=>`<div class="target"><span>${esc(p[0])}</span><strong>${target(p)}</strong></div>`).join('')}</div><button class="btn soft edit-params" data-eid="${e.id}">Parameters & Targets</button></div>`).join('');$$('.edit-params').forEach(b=>b.onclick=()=>editParameters(b.dataset.eid));$('#targetsList').innerHTML=es.map(e=>`<div class="rowcard"><h4>${esc(e.name)}</h4><div class="meta">${paramsForEquipment(e).filter(p=>p[2]!=='none').map(p=>`${p[0]} ${target(p)}`).join(' · ')||'No scored targets'}</div></div>`).join('');$('#facilityReports').innerHTML=state.reports.filter(r=>r.facility_id===f.id).map(rowReport).join('')}
function renderReports(){$('#reportsList').innerHTML=state.reports.length?state.reports.map(rowReport).join(''):'<div class="empty-state">No service reports yet.</div>'}
async function renderUsers(){if(state.profile?.role!=='admin')return;const [p,up]=await Promise.all([sb.from('profiles').select('*').order('display_name'),sb.from('user_permissions').select('*')]);if(p.error||up.error)return toast('Could not load users.');state.users=p.data;const perms=up.data;$('#usersList').innerHTML=p.data.map(u=>{const x=perms.find(z=>z.user_id===u.id)||{};return `<div class="user-card" data-uid="${u.id}"><div class="user-head"><div><h4>${esc(u.display_name||'Unnamed User')}</h4><div class="meta">${esc(u.role.replaceAll('_',' '))}</div></div><label class="active-toggle"><input type="checkbox" data-active ${u.active?'checked':''}> Active</label></div><div class="permission-grid"><label>Role<select data-role><option value="admin" ${u.role==='admin'?'selected':''}>Admin</option><option value="service_tech" ${u.role==='service_tech'?'selected':''}>Service Tech</option><option value="sales" ${u.role==='sales'?'selected':''}>Sales</option><option value="viewer" ${u.role==='viewer'?'selected':''}>Viewer</option></select></label>${[['manage_customers','Manage Customers'],['manage_facilities','Manage Facilities'],['manage_equipment','Manage Equipment'],['edit_targets','Edit Targets'],['create_reports','Create Reports'],['revise_completed_reports','Revise Completed'],['export_data','Export Data'],['manage_users','Manage Users']].map(([k,n])=>`<label class="perm-check"><input type="checkbox" data-perm="${k}" ${x[k]?'checked':''}> ${n}</label>`).join('')}</div><div class="user-actions"><button class="btn primary" data-save-user>Save Permissions</button></div></div>`}).join('');$('[data-save-user]').forEach(b=>b.onclick=()=>saveUserPermissions(b.closest('.user-card')))}
async function saveUserPermissions(card){const uid=card.dataset.uid,role=$('[data-role]',card).value,active=$('[data-active]',card).checked;const pr=await sb.from('profiles').update({role,active}).eq('id',uid);if(pr.error)return toast(pr.error.message);const vals={user_id:uid,updated_by:state.user.id};$('[data-perm]',card).forEach(x=>vals[x.dataset.perm]=x.checked);const q=await sb.from('user_permissions').upsert(vals);if(q.error)return toast(q.error.message);toast('User permissions saved.');await renderUsers()}
function populateReport(){if(!state.customers.length){$('#reportCustomer').innerHTML='<option value="">No customers yet</option>';$('#reportFacility').innerHTML='<option value="">No facilities yet</option>';$('#reportEquipment').innerHTML='<div class="card empty"><h3>No customer facilities configured</h3><p>Add a customer and facility before creating a service report.</p></div>';updateSnapshot();return}$('#reportCustomer').innerHTML=state.customers.map(c=>`<option value="${c.id}">${esc(c.name)}</option>`).join('');populateFacilities()}
function populateFacilities(){const cid=$('#reportCustomer').value||state.customers[0]?.id,fs=state.facilities.filter(f=>f.customer_id===cid);$('#reportFacility').innerHTML=fs.length?fs.map(f=>`<option value="${f.id}">${esc(f.name)}</option>`).join(''):'<option value="">No facilities yet</option>';buildReport()}
function buildReport(){const fid=$('#reportFacility').value;if(!fid){$('#reportEquipment').innerHTML='<div class="card empty"><h3>No facility selected</h3><p>Add a facility before entering service readings.</p></div>';updateSnapshot();return}$('#reportEquipment').innerHTML=state.equipment.filter(e=>e.facility_id===fid&&e.status==='active').sort(equipmentSort).map(e=>`<div class="system" data-eid="${e.id}" data-type="${e.type}"><div class="systemhead"><strong>${icon(e.type)} ${esc(e.name)}</strong><span>${e.equipment_class}</span></div><div class="systembody"><div class="readings">${paramsForEquipment(e).map((p,i)=>`<div class="reading"><label>${esc(p[0])}${p[2]!=='none'?` · ${target(p)}`:''}</label><input inputmode="decimal" data-pindex="${i}" ${p[5]==='auto'?'readonly placeholder="Auto-calculated" class="auto-reading"':''}><span class="pill gray">${p[5]==='auto'?'Waiting for Raw & Neutralized':'Not scored'}</span></div>`).join('')}</div><label style="display:block;margin-top:12px;font-size:12px;font-weight:800;color:#4c5968">Notes<textarea rows="3"></textarea></label></div></div>`).join('');$$('#reportEquipment input[data-pindex]').forEach(i=>i.oninput=updateSnapshot);updateSnapshot()}
function updateSnapshot(){
  let g=0,y=0,r=0,t=0;
  $$('#reportEquipment .system').forEach(s=>{
    const e=state.equipment.find(x=>x.id===s.dataset.eid), ps=paramsForEquipment(e), inputs=$$('input[data-pindex]',s);
    if(e.type==='boiler'){
      const raw=inputs.find(i=>ps[+i.dataset.pindex][1]==='raw_conductivity');
      const neu=inputs.find(i=>ps[+i.dataset.pindex][1]==='neutralized_conductivity');
      const alk=inputs.find(i=>ps[+i.dataset.pindex][1]==='alkalinity');
      if(raw&&neu&&alk){
        if(raw.value!==''&&neu.value!==''&&Number.isFinite(+raw.value)&&Number.isFinite(+neu.value)) alk.value=String(Math.round((+raw.value-+neu.value)*100)/100);
        else alk.value='';
      }
    }
    inputs.forEach(i=>{const p=ps[+i.dataset.pindex],s2=classify(p,i.value),pill=i.nextElementSibling;pill.className='pill '+(s2==='none'?'gray':s2);pill.textContent=s2==='green'?'In Range':s2==='yellow'?'Slightly Out':s2==='red'?'Out of Range':(p[5]==='auto'?'Waiting for Raw & Neutralized':'Not scored');if(s2!=='none'){t++;if(s2==='green')g++;if(s2==='yellow')y++;if(s2==='red')r++}})
  });
  $('#mTested').textContent=t;$('#mGreen').textContent=g;$('#mYellow').textContent=y;$('#mRed').textContent=r;let text='No Data',cl='neutral';if(t){if(r||y/t>.3){text='Needs Attention';cl='red'}else if(y){text='Watch';cl='yellow'}else{text='Stable';cl='green'}}$('#programStatus').textContent=text;$('#programStatus').className='program '+cl
}
function collectReport(){
  updateSnapshot();
  const systems=$$('#reportEquipment .system').map(s=>{const e=state.equipment.find(x=>x.id===s.dataset.eid),ps=paramsForEquipment(e);return{equipment:e,notes:$('textarea',s)?.value.trim()||'',readings:$$('input[data-pindex]',s).map(i=>{const p=ps[+i.dataset.pindex];return{parameter:p,value:i.value.trim(),status:classify(p,i.value)}})}});
  return{technician:$('#technician').value.trim(),date:$('#serviceDate').value,summary:$('#summary').value.trim(),program_status:$('#programStatus').textContent,systems}
}
function reportMetrics(payload){const scored=payload.systems.flatMap(s=>s.readings).filter(x=>x.value!==''&&x.status!=='none');return{tested:scored.length,green:scored.filter(x=>x.status==='green').length,yellow:scored.filter(x=>x.status==='yellow').length,red:scored.filter(x=>x.status==='red').length}}
function statusText(s){return s==='green'?'In Range':s==='yellow'?'Slightly Out':s==='red'?'Out of Range':'—'}
function pdfTarget(p){return p[2]==='range'?`${p[3]}-${p[4]}`:p[2]==='min'?`>= ${p[3]}`:p[2]==='max'?`< ${p[4]}`:'—'}
async function saveReport(status){
  const fid=$('#reportFacility').value,ps=$('#programStatus').textContent,f=facility(fid),c=customer(f.customer_id),payload=collectReport();
  if(!fid)return toast('Choose a facility.');
  const entered=payload.systems.some(s=>s.notes||s.readings.some(x=>x.value!==''))||payload.summary;
  if(status==='completed'&&!entered)return toast('Enter at least one reading or note before completing the report.');
  if(DEMO){const r={id:'r'+Date.now(),report_number:Math.max(...state.reports.map(x=>x.report_number))+1,facility_id:fid,service_date:payload.date,status,program_status:ps==='No Data'?null:ps};state.reports.unshift(r);if(status==='completed')await makePDF(r,c,f,payload);render();toast(status==='completed'?'Report completed.':'Draft saved.');return}
  try{
    const base={facility_id:fid,technician_id:state.user.id,service_date:payload.date,overall_notes:payload.summary,program_status:ps,status,created_by:state.user.id,updated_by:state.user.id,completed_at:status==='completed'?new Date().toISOString():null};
    const rr=await sb.from('reports').insert(base).select('*').single();if(rr.error)throw rr.error;
    for(const sys of payload.systems){
      const used=sys.readings.filter(x=>x.value!=='');if(!used.length&&!sys.notes)continue;
      const re=await sb.from('report_equipment').insert({report_id:rr.data.id,equipment_id:sys.equipment.id,equipment_type_code:sys.equipment.type,equipment_name:sys.equipment.name,equipment_class:sys.equipment.equipment_class,notes:sys.notes,sort_order:(state.equipmentTypes.find(x=>x.code===sys.equipment.type)?.sort_order??90)*100+(sys.equipment.sort_order??0)}).select('*').single();if(re.error)throw re.error;
      const rows=used.map((x,i)=>({report_equipment_id:re.data.id,parameter_code:x.parameter[1],parameter_name:x.parameter[0],unit:null,input_type:x.parameter[5]==='auto'?'calculated':'manual',numeric_value:Number.isFinite(+x.value)?+x.value:null,text_value:Number.isFinite(+x.value)?null:x.value,target_type:x.parameter[2]==='min'?'minimum':x.parameter[2]==='max'?'maximum':x.parameter[2],target_min:x.parameter[3],target_max:x.parameter[4],warning_min:x.parameter[6]??null,warning_max:x.parameter[7]??null,target_label:pdfTarget(x.parameter),reading_status:x.status==='green'?'in_range':x.status==='yellow'?'slightly_out':x.status==='red'?'out_of_range':'no_target',sort_order:i}));
      if(rows.length){const ri=await sb.from('report_readings').insert(rows);if(ri.error)throw ri.error}
    }
    if(status==='completed')await makePDF(rr.data,c,f,payload);
    await loadSupabase();toast(status==='completed'?'Report completed.':'Draft saved.');
  }catch(e){console.error(e);toast(e.message||'Could not save report.')}
}
async function loadPdfHeader(){return new Promise(resolve=>{const img=new Image();img.onload=()=>{try{const canvas=document.createElement('canvas');canvas.width=img.naturalWidth;canvas.height=img.naturalHeight;canvas.getContext('2d').drawImage(img,0,0);resolve({data:canvas.toDataURL('image/png'),width:img.naturalWidth,height:img.naturalHeight})}catch(e){resolve(null)}};img.onerror=()=>resolve(null);img.src='Header%202025.png?v=20261008-2'})}
async function makePDF(r,c,f,payload){
  const{jsPDF}=window.jspdf,doc=new jsPDF('p','pt','letter'),W=doc.internal.pageSize.getWidth(),H=doc.internal.pageSize.getHeight(),L=48,R=48,contentW=W-L-R;let y=42;
  const headerAsset=await loadPdfHeader();
  const drawHeader=first=>{
    if(headerAsset){
      const maxW=W-48,scaledH=maxW*(headerAsset.height/headerAsset.width);
      doc.addImage(headerAsset.data,'PNG',24,18,maxW,scaledH,undefined,'FAST');
      y=18+scaledH+18;
    }else{
      doc.setFillColor(11,47,89);doc.rect(0,0,W,8,'F');
      doc.setFont('helvetica','bold');doc.setFontSize(18);doc.setTextColor(11,47,89);doc.text('B & L Neeley, Inc.',L,34);
      doc.setFont('helvetica','normal');doc.setFontSize(8.5);doc.setTextColor(88,99,111);doc.text('WATER TECHNOLOGIES  •  CLEANING COMPOUNDS  •  PROCESS SOLUTIONS',L,49);
      doc.setDrawColor(215,224,233);doc.line(L,59,W-R,59);y=78;
    }
    if(first){doc.setFont('helvetica','bold');doc.setFontSize(16);doc.setTextColor(23,34,48);doc.text('SERVICE REPORT',L,y);y+=20;doc.setFont('helvetica','normal');doc.setFontSize(9);doc.setTextColor(95,105,115);doc.text('Water, Boiler & Cooling Systems',L,y);y+=16}
  };
  const newPage=()=>{doc.addPage();drawHeader(false)};
  const ensure=n=>{if(y+n>H-62)newPage()};
  drawHeader(true);

  doc.autoTable({startY:y,margin:{left:L,right:R},theme:'plain',
    body:[['Customer',c.name,'Facility',f.name],['Service Technician',payload.technician||'—','Date',payload.date],['Program Status',payload.program_status,'Report #',String(r.report_number)]],
    styles:{fontSize:9,cellPadding:5,textColor:[35,45,55]},
    columnStyles:{0:{fontStyle:'bold',textColor:[11,47,89],cellWidth:92},1:{cellWidth:158},2:{fontStyle:'bold',textColor:[11,47,89],cellWidth:80}}
  });y=doc.lastAutoTable.finalY+15;

  const m=reportMetrics(payload);
  doc.setFont('helvetica','bold');doc.setFontSize(11);doc.setTextColor(11,47,89);doc.text('Program Snapshot',L,y);y+=8;
  doc.autoTable({startY:y,margin:{left:L,right:R},theme:'grid',head:[['Points Tested','In Range','Slightly Out','Out of Range']],body:[[m.tested,m.green,m.yellow,m.red]],
    headStyles:{fillColor:[11,47,89],textColor:255,halign:'center',fontSize:8},
    bodyStyles:{halign:'center',fontStyle:'bold',fontSize:11,cellPadding:7},
    styles:{lineColor:[222,229,236],lineWidth:.5}
  });y=doc.lastAutoTable.finalY+18;

  payload.systems.forEach(sys=>{
    const used=sys.readings.filter(x=>x.value!=='');
    const rows=used.map(x=>[x.parameter[0],x.value,x.parameter[2]==='none'?'—':pdfTarget(x.parameter),statusText(x.status)]);
    if(!rows.length&&!sys.notes)return;

    // Estimate the complete system block. If it will fit on a fresh page but not
    // in the remaining space, move the whole system to the next page.
    const noteLines=sys.notes?doc.splitTextToSize(sys.notes,contentW):[];
    const estimated=30+(rows.length?30+rows.length*23:0)+(sys.notes?25+noteLines.length*10:0)+10;
    const freshCapacity=H-78-62;
    if(y+estimated>H-62 && estimated<=freshCapacity)newPage();
    else ensure(70);

    doc.setFillColor(11,47,89);doc.roundedRect(L,y,contentW,24,4,4,'F');
    doc.setFont('helvetica','bold');doc.setFontSize(10.5);doc.setTextColor(255);doc.text(sys.equipment.name,L+10,y+16);y+=30;

    if(rows.length){
      doc.autoTable({startY:y,margin:{left:L,right:R,bottom:62},theme:'grid',
        head:[['Parameter','Result','Target','Status']],body:rows,
        headStyles:{fillColor:[233,239,245],textColor:[11,47,89],fontStyle:'bold',fontSize:8},
        styles:{fontSize:8.5,cellPadding:5,lineColor:[222,229,236],lineWidth:.5},
        showHead:'everyPage',
        didDrawPage:data=>{
          // When AutoTable itself creates a continuation page, add the normal
          // B&L page header above the continuation table.
          if(data.pageNumber>1&&headerAsset){
            const maxW=W-48,scaledH=maxW*(headerAsset.height/headerAsset.width);
            doc.addImage(headerAsset.data,'PNG',24,18,maxW,scaledH,undefined,'FAST');
          }
        },
        didParseCell:d=>{
          if(d.section==='body'&&(d.column.index===1||d.column.index===3)){
            const s=used[d.row.index]?.status;
            d.cell.styles.fillColor=s==='green'?[212,237,218]:s==='yellow'?[255,243,205]:s==='red'?[248,215,218]:[255,255,255]
          }
        }
      });y=doc.lastAutoTable.finalY+9
    }

    if(sys.notes){
      const lines=doc.splitTextToSize(sys.notes,contentW);
      ensure(24+lines.length*10);
      doc.setFont('helvetica','bold');doc.setFontSize(8.5);doc.setTextColor(11,47,89);doc.text('Notes',L,y);y+=11;
      doc.setFont('helvetica','normal');doc.setTextColor(45,55,65);doc.text(lines,L,y);y+=lines.length*10+7
    }
    y+=8
  });

  if(payload.summary){
    const lines=doc.splitTextToSize(payload.summary,contentW);
    ensure(32+lines.length*10);
    doc.setFont('helvetica','bold');doc.setFontSize(11);doc.setTextColor(11,47,89);doc.text('Summary & Recommendations',L,y);y+=14;
    doc.setFont('helvetica','normal');doc.setFontSize(9);doc.setTextColor(35,45,55);doc.text(lines,L,y)
  }

  const pages=doc.getNumberOfPages();
  for(let i=1;i<=pages;i++){
    doc.setPage(i);doc.setDrawColor(220,226,232);doc.line(L,H-37,W-R,H-37);
    doc.setFont('helvetica','normal');doc.setFontSize(7.2);doc.setTextColor(110,118,127);
    doc.text('B & L Neeley, Inc. • Water Technologies & Cleaning Compounds • 209-823-3571',L,H-22);
    doc.text(`Page ${i} of ${pages}`,W-R,H-22,{align:'right'})
  }
  const safe=s=>String(s).replace(/[^a-z0-9]+/gi,'_').replace(/^_+|_+$/g,'');
  doc.save(`${safe(c.name)}_${safe(f.name)}_Report_${r.service_date}.pdf`)
}
function go(id){$$('.route').forEach(x=>x.classList.remove('active'));$('#'+id).classList.add('active');$$('.nav').forEach(x=>x.classList.toggle('active',x.dataset.route===id));const names={'dashboard':['Dashboard','Service program overview'],'customers':['Customers','Customer and facility management'],'reports':['Service Reports','History, revisions, PDFs, and exports'],'new-report':['New Service Report','Field service entry'],'facility':['Facility Setup','Equipment, targets, reports, and trends'],'users':['Users & Permissions','Administration and access control']};$('#pageTitle').textContent=names[id][0];$('#pageSubtitle').textContent=names[id][1];scrollTo({top:0,behavior:'smooth'})}
function openModal(title,body){$('#modalTitle').textContent=title;$('#modalBody').innerHTML=body;$('#modal').classList.remove('hidden')}function closeModal(){$('#modal').classList.add('hidden')}function toast(s){$('#toast').textContent=s;$('#toast').classList.remove('hidden');setTimeout(()=>$('#toast').classList.add('hidden'),2500)}
function addEquipment(fromReport=false){const fid=fromReport?$('#reportFacility').value:state.facilityId;if(!fid)return toast('Create or select a facility first.');const opts=state.equipmentTypes.filter(x=>x.active!==false).sort((a,b)=>a.sort_order-b.sort_order).map(x=>`<option value="${x.code}">${esc(x.display_name)}</option>`).join('');openModal('Add Equipment',`<div class="formgrid"><label>System Type<select id="mType">${opts}</select></label><label>Custom Name <span class="meta">(optional)</span><input id="mName" placeholder="e.g. Hot Water Loop #1"></label><label>Equipment Tag <span class="meta">(optional)</span><input id="mTag" placeholder="e.g. BLR-02"></label><label>Equipment Class<select id="mClass"><option value="permanent">Permanent</option><option value="rental">Rental</option><option value="temporary">Temporary</option></select></label></div><p class="meta" style="margin-top:12px">The system type controls report order and loads the B&L default parameters. You can customize parameters and targets after adding it.</p><div class="modalactions"><button class="btn" id="cancel">Cancel</button><button class="btn primary" id="saveEq">Add Equipment</button></div>`);$('#cancel').onclick=closeModal;$('#saveEq').onclick=async()=>{try{const t=state.equipmentTypes.find(x=>x.code===$('#mType').value);const n=$('#mName').value.trim()||t?.display_name;if(!t)throw new Error('Equipment type not found.');const ins=await sb.from('facility_equipment').insert({facility_id:fid,equipment_type_id:t.id,name:n,tag:$('#mTag').value.trim()||null,class:$('#mClass').value,active:true,created_by:state.user.id}).select().single();if(ins.error)throw ins.error;closeModal();toast('Equipment added with default parameters.');await loadSupabase();if(fromReport)buildReport()}catch(e){toast(e.message)}}}
async function editParameters(eid){const e=state.equipment.find(x=>x.id===eid);if(!e)return;const rows=state.targets.filter(x=>x.facility_equipment_id===eid&&x.active!==false).sort((a,b)=>a.sort_order-b.sort_order);openModal('Parameters — '+e.name,`<div id="paramEditor">${rows.map((x,i)=>paramEditorRow(x,i)).join('')}</div><div class="modalactions"><button class="btn soft" id="addParam">+ Custom Parameter</button><button class="btn soft" id="applyParams">Apply to Other Equipment</button><button class="btn" id="cancel">Cancel</button><button class="btn primary" id="saveParams">Save Parameters</button></div>`);$('#cancel').onclick=closeModal;$('#addParam').onclick=()=>{$('#paramEditor').insertAdjacentHTML('beforeend',paramEditorRow({parameter_name:'',parameter_code:'',unit:'',target_type:'none'},$('#paramEditor').children.length))};$('#applyParams').onclick=()=>applyParametersModal(eid);$('#saveParams').onclick=()=>saveParameters(eid)}
function paramEditorRow(x,i){return `<div class="rowcard param-edit" data-id="${x.id||''}"><div class="formgrid"><label>Parameter<input data-pname value="${esc(x.parameter_name||'')}" placeholder="e.g. Iron"></label><label>Unit<input data-unit value="${esc(x.unit||'')}" placeholder="ppm"></label><label>Target Type<select data-tt><option value="none" ${x.target_type==='none'?'selected':''}>No Target</option><option value="range" ${x.target_type==='range'?'selected':''}>Range</option><option value="minimum" ${x.target_type==='minimum'?'selected':''}>Minimum</option><option value="maximum" ${x.target_type==='maximum'?'selected':''}>Maximum</option></select></label><label>Target Min<input inputmode="decimal" data-tmin value="${x.target_min??''}"></label><label>Target Max<input inputmode="decimal" data-tmax value="${x.target_max??''}"></label><label>Warning Min<input inputmode="decimal" data-wmin value="${x.warning_min??''}"></label><label>Warning Max<input inputmode="decimal" data-wmax value="${x.warning_max??''}"></label><label>Order<input inputmode="numeric" data-order value="${x.sort_order??(i+1)*10}"></label></div><label class="perm-check"><input type="checkbox" data-active ${x.active===false?'':'checked'}> Active on reports</label></div>`}
async function saveParameters(eid){const cards=$$('.param-edit',$('#paramEditor'));for(let i=0;i<cards.length;i++){const c=cards[i],name=$('[data-pname]',c).value.trim();if(!name)continue;const code=(c.dataset.id?state.targets.find(x=>x.id===c.dataset.id)?.parameter_code:null)||name.toLowerCase().replace(/[^a-z0-9]+/g,'_').replace(/^_|_$/g,'');const num=k=>{const v=$(k,c).value.trim();return v===''?null:+v};const row={facility_equipment_id:eid,parameter_code:code,parameter_name:name,unit:$('[data-unit]',c).value.trim()||null,input_type:'manual',target_type:$('[data-tt]',c).value,target_min:num('[data-tmin]'),target_max:num('[data-tmax]'),warning_min:num('[data-wmin]'),warning_max:num('[data-wmax]'),sort_order:+$('[data-order]',c).value||i*10,active:$('[data-active]',c).checked,updated_by:state.user.id};const q=c.dataset.id?await sb.from('equipment_targets').update(row).eq('id',c.dataset.id):await sb.from('equipment_targets').insert(row);if(q.error)return toast(q.error.message)}closeModal();await loadSupabase();toast('Parameters and targets saved.')}
async function applyParametersModal(sourceId){const src=state.equipment.find(x=>x.id===sourceId);if(!src)return;const others=state.equipment.filter(x=>x.facility_id===src.facility_id&&x.type===src.type&&x.id!==sourceId&&x.status==='active');if(!others.length)return toast('No other '+(types[src.type]||'matching')+' equipment at this facility.');openModal('Apply '+src.name+' Configuration',`<p class="meta">This copies the current parameter list, units, targets, warning bands and parameter order. Equipment names, tags and classes are not changed.</p><div class="permission-grid" id="copyTargets">${others.map(x=>`<label><input type="checkbox" value="${x.id}"> ${esc(x.name)}</label>`).join('')}</div><div class="modalactions"><button class="btn soft" id="selectAllEq">Select All</button><button class="btn" id="cancelCopy">Cancel</button><button class="btn primary" id="copyConfig">Apply Configuration</button></div>`);$('#cancelCopy').onclick=()=>editParameters(sourceId);$('#selectAllEq').onclick=()=>$$('#copyTargets input').forEach(x=>x.checked=true);$('#copyConfig').onclick=async()=>{const ids=$$('#copyTargets input:checked').map(x=>x.value);if(!ids.length)return toast('Select at least one piece of equipment.');const srcRows=state.targets.filter(x=>x.facility_equipment_id===sourceId).sort((a,b)=>a.sort_order-b.sort_order);for(const id of ids){const del=await sb.from('equipment_targets').delete().eq('facility_equipment_id',id);if(del.error)return toast(del.error.message);if(srcRows.length){const copies=srcRows.map(x=>({facility_equipment_id:id,parameter_code:x.parameter_code,parameter_name:x.parameter_name,unit:x.unit,input_type:x.input_type,calculation_code:x.calculation_code,target_type:x.target_type,target_min:x.target_min,target_max:x.target_max,warning_min:x.warning_min,warning_max:x.warning_max,sort_order:x.sort_order,active:x.active,updated_by:state.user.id}));const ins=await sb.from('equipment_targets').insert(copies);if(ins.error)return toast(ins.error.message)}}closeModal();await loadSupabase();toast('Configuration applied to '+ids.length+' equipment item'+(ids.length===1?'':'s')+'.')}}
async function loadSupabase(){if(DEMO)return;const[c,f,t,e,tar,r]=await Promise.all([sb.from('customers').select('*').eq('active',true).order('name'),sb.from('facilities').select('*').eq('active',true).order('name'),sb.from('equipment_types').select('*').eq('active',true).order('sort_order'),sb.from('facility_equipment').select('*').eq('active',true).order('sort_order'),sb.from('equipment_targets').select('*').eq('active',true).order('sort_order'),sb.from('reports').select('*').order('service_date',{ascending:false})]);const err=[c,f,t,e,tar,r].find(x=>x.error);if(err){console.error(err.error);return toast('Could not load Supabase data.')}state.customers=c.data;state.facilities=f.data;state.equipmentTypes=t.data;state.targets=tar.data;state.equipment=e.data.map(x=>{const et=t.data.find(z=>z.id===x.equipment_type_id);return{id:x.id,facility_id:x.facility_id,type:et?.code||'other',name:x.name,equipment_class:x.class,sort_order:x.sort_order,status:x.active?'active':'inactive'}});state.reports=r.data;state.facilityId=state.facilityId&&state.facilities.some(x=>x.id===state.facilityId)?state.facilityId:state.facilities[0]?.id;if(state.facilityId)render();else{renderDashboard();renderCustomers();renderReports();populateReport()}}
async function boot(){if(DEMO){showLogin();$('#loginError').textContent='Service Platform is not connected to Supabase.';return}const sess=await sb.auth.getSession();if(sess.data.session)await onSignedIn(sess.data.session.user);else showLogin();sb.auth.onAuthStateChange((event,session)=>{if(event==='SIGNED_OUT')showLogin()})}
function showLogin(){$('#authGate').classList.remove('hidden');$('.app').classList.add('hidden');$('.mobile-nav').classList.add('hidden');state.user=null;state.profile=null}
async function onSignedIn(user){state.user=user;const [p,up]=await Promise.all([sb.from('profiles').select('*').eq('id',user.id).single(),sb.from('user_permissions').select('*').eq('user_id',user.id).maybeSingle()]);if(p.error){console.error(p.error);return showLogin()}state.profile=p.data;state.permissions=up.data;if(!p.data.active){await sb.auth.signOut();return}$('#signedInUser').textContent=p.data.display_name||user.email;$$('.admin-only').forEach(x=>x.classList.toggle('hidden',p.data.role!=='admin'));$('#authGate').classList.add('hidden');$('.app').classList.remove('hidden');$('.mobile-nav').classList.remove('hidden');await loadSupabase()}
$$('[data-route]').forEach(x=>x.onclick=()=>go(x.dataset.route));$$('.tab').forEach(x=>x.onclick=()=>{$$('.tab').forEach(t=>t.classList.remove('active'));$$('.tabpane').forEach(t=>t.classList.remove('active'));x.classList.add('active');$('#'+x.dataset.tab).classList.add('active')});$('#customerSearch').oninput=renderCustomers;$('#reportCustomer').onchange=populateFacilities;$('#reportFacility').onchange=buildReport;$('#addEquipment').onclick=()=>addEquipment(false);$('#addEquipmentReport').onclick=()=>addEquipment(true);$('#closeModal').onclick=closeModal;$('#saveDraft').onclick=()=>saveReport('draft');$('#completeReport').onclick=()=>saveReport('completed');$('#addCustomer').onclick=()=>{if(!state.profile||state.profile.role!=='admin')return toast('Admin access required.');openModal('Add Customer','<label>Customer Name<input id="mCustomerName" placeholder="Customer name"></label><div class="modalactions"><button class="btn" id="cancel">Cancel</button><button class="btn primary" id="saveCustomer">Add Customer</button></div>');$('#cancel').onclick=closeModal;$('#saveCustomer').onclick=async()=>{const name=$('#mCustomerName').value.trim();if(!name)return toast('Enter a customer name.');const q=await sb.from('customers').insert({name}).select().single();if(q.error)return toast(q.error.message);closeModal();await loadSupabase();toast('Customer added.')}};$('#serviceDate').value=new Date().toISOString().slice(0,10);
$('#loginForm').onsubmit=async e=>{e.preventDefault();$('#loginError').textContent='';const btn=$('#loginForm button[type="submit"]');btn.disabled=true;btn.textContent='Signing In...';try{const q=await sb.auth.signInWithPassword({email:$('#loginEmail').value.trim(),password:$('#loginPassword').value});if(q.error)throw q.error;if(!q.data.user)throw new Error('Sign in did not return a user.');await onSignedIn(q.data.user)}catch(err){$('#loginError').textContent=err.message||'Could not sign in.'}finally{btn.disabled=false;btn.textContent='Sign In'}};$('#signOut').onclick=async()=>{const btn=$('#signOut');btn.disabled=true;btn.textContent='Signing Out...';try{const q=await sb.auth.signOut();if(q.error)throw q.error;showLogin();$('#loginEmail').value='';$('#loginPassword').value='';$('#loginError').textContent=''}catch(err){toast(err.message||'Could not sign out.')}finally{btn.disabled=false;btn.textContent='Sign Out'}};boot();
})();
