(()=>{
const cfg=window.BLN_CONFIG||{};const DEMO=cfg.DEMO_MODE||!cfg.SUPABASE_URL||!cfg.SUPABASE_ANON_KEY;const sb=!DEMO?window.supabase.createClient(cfg.SUPABASE_URL,cfg.SUPABASE_ANON_KEY):null;
const state={customers:[{id:'c1',name:'Nulaid'},{id:'c2',name:'Yosemite Foods'},{id:'c3',name:'Refresco'}],facilities:[{id:'f1',customer_id:'c1',name:'Ripon',city:'Ripon',state:'CA'},{id:'f2',customer_id:'c2',name:'Modesto',city:'Modesto',state:'CA'},{id:'f3',customer_id:'c3',name:'Modesto',city:'Modesto',state:'CA'}],equipment:[],reports:[],facilityId:'f1'};
const $=(s,r=document)=>r.querySelector(s),$$=(s,r=document)=>[...r.querySelectorAll(s)];
const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
const types={raw_water:'Raw Water',soft_water:'Soft Water',softener:'Water Softener',ro_water:'RO Water',feed_water:'Feed Water',feed_tank:'Feed Water Tank',boiler:'Boiler',cooling_tower:'Cooling Tower',other:'Other'};
function eq(id,f,t,n,c='permanent'){return{id,facility_id:f,type:t,name:n,equipment_class:c,status:'active'}}
state.equipment=[eq('e1','f1','raw_water','Raw Water'),eq('e2','f1','soft_water','Soft Water'),eq('e3','f1','boiler','Boiler #1'),eq('e4','f1','boiler','Rental Boiler #1','rental'),eq('e5','f1','cooling_tower','Cooling Tower #1'),eq('e6','f2','raw_water','Raw Water'),eq('e7','f2','feed_tank','Feed Tank'),eq('e8','f2','boiler','Boiler #1'),eq('e9','f3','soft_water','Soft Water'),eq('e10','f3','boiler','Boiler #1')];
state.reports=[{id:'r1',report_number:842,facility_id:'f1',service_date:'2026-09-10',status:'completed',program_status:'Stable'},{id:'r2',report_number:841,facility_id:'f2',service_date:'2026-09-09',status:'revised',program_status:'Watch'},{id:'r3',report_number:840,facility_id:'f3',service_date:'2026-09-08',status:'draft',program_status:null}];
function params(t){if(t==='boiler')return[['Raw Conductivity','raw_conductivity','none',null,null],['Neutralized Conductivity','neutralized_conductivity','range',2500,3000],['Alkalinity','alkalinity','min',400,null,'auto'],['OH Alkalinity','oh_alkalinity','min',150,null],['pH','ph','min',10.8,null],['Phosphate','phosphate','range',35,50],['Sulfite','sulfite','range',30,60]];if(t==='cooling_tower')return[['Hardness','hardness','max',null,350],['Conductivity','conductivity','range',1200,1500],['pH','ph','range',7,9],['Phosphonate','phosphonate','range',8,12],['Biocide','biocide','none',null,null]];return[['pH','ph','none',null,null],['Conductivity','conductivity','none',null,null],['Hardness','hardness',t==='raw_water'?'none':'range',0,4],['Alkalinity','alkalinity','none',null,null]]}
function target(p){return p[2]==='range'?`${p[3]}–${p[4]}`:p[2]==='min'?`≥${p[3]}`:p[2]==='max'?`<${p[4]}`:'—'}
function classify(p,v){if(v===''||p[2]==='none')return'none';v=+v;if(p[2]==='range')return v>=p[3]&&v<=p[4]?'green':((v>=p[3]*.9&&v<p[3])||(v>p[4]&&v<=p[4]*1.1))?'yellow':'red';if(p[2]==='min')return v>=p[3]?'green':v>=p[3]*.9?'yellow':'red';if(p[2]==='max')return v<=p[4]?'green':v<=p[4]*1.1?'yellow':'red';return'none'}
function facility(id){return state.facilities.find(x=>x.id===id)}function customer(id){return state.customers.find(x=>x.id===id)}function icon(t){return t==='boiler'?'B':t==='cooling_tower'?'CT':'W'}
function rowReport(r){const f=facility(r.facility_id),c=customer(f.customer_id),cl=r.program_status==='Stable'?'green':r.program_status==='Watch'?'yellow':r.program_status?'red':'gray';return`<div class="rowcard"><div class="rowtop"><div><h4>${esc(c.name)} — ${esc(f.name)}</h4><div class="meta">${r.service_date} · Report #${r.report_number}</div></div><span class="badge ${cl}">${esc(r.program_status||r.status)}</span></div></div>`}
function render(){renderDashboard();renderCustomers();renderFacility();renderReports();populateReport()}
function renderDashboard(){$('#recentReports').innerHTML=state.reports.map(rowReport).join('');$('#recentEquipment').innerHTML=state.equipment.slice(-5).reverse().map(e=>`<div class="rowcard"><strong>${esc(e.name)}</strong><div class="meta">${esc(facility(e.facility_id).name)} · ${e.equipment_class}</div></div>`).join('')}
function renderCustomers(){const q=$('#customerSearch').value.toLowerCase();$('#customerList').innerHTML=state.customers.filter(c=>c.name.toLowerCase().includes(q)).map(c=>{const fs=state.facilities.filter(f=>f.customer_id===c.id),n=state.equipment.filter(e=>fs.some(f=>f.id===e.facility_id)).length;return`<div class="rowcard customer" data-id="${c.id}"><div class="rowtop"><div><h4>${esc(c.name)}</h4><div class="meta">${fs.length} facilit${fs.length===1?'y':'ies'} · ${n} active systems</div></div><span class="badge gray">Open</span></div></div>`}).join('');$$('.customer').forEach(x=>x.onclick=()=>{const f=state.facilities.find(z=>z.customer_id===x.dataset.id);if(f){state.facilityId=f.id;renderFacility();go('facility')}})}
function renderFacility(){const f=facility(state.facilityId),c=customer(f.customer_id);$('#facilityTitle').textContent=`${c.name} — ${f.name}`;const es=state.equipment.filter(e=>e.facility_id===f.id);$('#equipmentGrid').innerHTML=es.map(e=>`<div class="card equipment"><div class="eqtop"><div class="icon">${icon(e.type)}</div><span class="badge green">${e.equipment_class==='rental'?'Rental':'Active'}</span></div><h4>${esc(e.name)}</h4><div class="meta">${esc(types[e.type])} · ${e.equipment_class}</div><div class="targets">${params(e.type).filter(p=>p[2]!=='none').slice(0,3).map(p=>`<div class="target"><span>${esc(p[0])}</span><strong>${target(p)}</strong></div>`).join('')}</div></div>`).join('');$('#targetsList').innerHTML=es.map(e=>`<div class="rowcard"><h4>${esc(e.name)}</h4><div class="meta">${params(e.type).filter(p=>p[2]!=='none').map(p=>`${p[0]} ${target(p)}`).join(' · ')||'No scored targets'}</div></div>`).join('');$('#facilityReports').innerHTML=state.reports.filter(r=>r.facility_id===f.id).map(rowReport).join('')}
function renderReports(){$('#reportsList').innerHTML=state.reports.map(rowReport).join('')}
function populateReport(){$('#reportCustomer').innerHTML=state.customers.map(c=>`<option value="${c.id}">${esc(c.name)}</option>`).join('');populateFacilities()}
function populateFacilities(){const cid=$('#reportCustomer').value||state.customers[0].id;$('#reportFacility').innerHTML=state.facilities.filter(f=>f.customer_id===cid).map(f=>`<option value="${f.id}">${esc(f.name)}</option>`).join('');buildReport()}
function buildReport(){const fid=$('#reportFacility').value;$('#reportEquipment').innerHTML=state.equipment.filter(e=>e.facility_id===fid&&e.status==='active').map(e=>`<div class="system" data-eid="${e.id}" data-type="${e.type}"><div class="systemhead"><strong>${icon(e.type)} ${esc(e.name)}</strong><span>${e.equipment_class}</span></div><div class="systembody"><div class="readings">${params(e.type).map((p,i)=>`<div class="reading"><label>${esc(p[0])}${p[2]!=='none'?` · ${target(p)}`:''}</label><input inputmode="decimal" data-pindex="${i}" ${p[5]==='auto'?'readonly placeholder="Auto-calculated" class="auto-reading"':''}><span class="pill gray">${p[5]==='auto'?'Waiting for Raw & Neutralized':'Not scored'}</span></div>`).join('')}</div><label style="display:block;margin-top:12px;font-size:12px;font-weight:800;color:#4c5968">Notes<textarea rows="3"></textarea></label></div></div>`).join('');$$('#reportEquipment input[data-pindex]').forEach(i=>i.oninput=updateSnapshot);updateSnapshot()}
function updateSnapshot(){
  let g=0,y=0,r=0,t=0;
  $$('#reportEquipment .system').forEach(s=>{
    const e=state.equipment.find(x=>x.id===s.dataset.eid), ps=params(e.type), inputs=$$('input[data-pindex]',s);
    if(e.type==='boiler'){
      const raw=inputs.find(i=>ps[+i.dataset.pindex][1]==='raw_conductivity');
      const neu=inputs.find(i=>ps[+i.dataset.pindex][1]==='neutralized_conductivity');
      const alk=inputs.find(i=>ps[+i.dataset.pindex][1]==='alkalinity');
      if(raw&&neu&&alk){
        if(raw.value!==''&&neu.value!==''&&Number.isFinite(+raw.value)&&Number.isFinite(+neu.value)) alk.value=String(Math.round((+raw.value-+neu.value)*100)/100);
        else alk.value='';
      }
    }
    inputs.forEach(i=>{const p=ps[+i.dataset.pindex],s2=classify(p,i.value),pill=i.nextElementSibling;pill.className='pill '+(s2==='none'?'gray':s2);pill.textContent=s2==='green'?'In Range':s2==='yellow'?'Slightly Out':s2==='red'?'Out of Range':(p[5]==='auto'?'Waiting for Raw & Neutralized':'Not scored');if(s2!=='none'){t++;if(s2==='green')g++;if(s2==='yellow')y++;if(s2==='red')r++}})
  });
  $('#mTested').textContent=t;$('#mGreen').textContent=g;$('#mYellow').textContent=y;$('#mRed').textContent=r;let text='No Data',cl='neutral';if(t){if(r||y/t>.3){text='Needs Attention';cl='red'}else if(y){text='Watch';cl='yellow'}else{text='Stable';cl='green'}}$('#programStatus').textContent=text;$('#programStatus').className='program '+cl
}
function collectReport(){
  updateSnapshot();
  const systems=$$('#reportEquipment .system').map(s=>{const e=state.equipment.find(x=>x.id===s.dataset.eid),ps=params(e.type);return{equipment:e,notes:$('textarea',s)?.value.trim()||'',readings:$$('input[data-pindex]',s).map(i=>{const p=ps[+i.dataset.pindex];return{parameter:p,value:i.value.trim(),status:classify(p,i.value)}})}});
  return{technician:$('#technician').value.trim(),date:$('#serviceDate').value,summary:$('#summary').value.trim(),program_status:$('#programStatus').textContent,systems}
}
function reportMetrics(payload){const scored=payload.systems.flatMap(s=>s.readings).filter(x=>x.value!==''&&x.status!=='none');return{tested:scored.length,green:scored.filter(x=>x.status==='green').length,yellow:scored.filter(x=>x.status==='yellow').length,red:scored.filter(x=>x.status==='red').length}}
function statusText(s){return s==='green'?'In Range':s==='yellow'?'Slightly Out':s==='red'?'Out of Range':'—'}
async function saveReport(status){
  const fid=$('#reportFacility').value,ps=$('#programStatus').textContent,f=facility(fid),c=customer(f.customer_id),payload=collectReport();
  if(!fid)return toast('Choose a facility.');
  const entered=payload.systems.some(s=>s.notes||s.readings.some(x=>x.value!==''))||payload.summary;
  if(status==='completed'&&!entered)return toast('Enter at least one reading or note before completing the report.');
  if(DEMO){const r={id:'r'+Date.now(),report_number:Math.max(...state.reports.map(x=>x.report_number))+1,facility_id:fid,service_date:payload.date,status,program_status:ps==='No Data'?null:ps};state.reports.unshift(r);if(status==='completed')makePDF(r,c,f,payload);render();toast(status==='completed'?'Report completed.':'Draft saved.');return}
  toast('Supabase save is wired for the next pass after the test schema is connected.')
}
function makePDF(r,c,f,payload){
  const{jsPDF}=window.jspdf,doc=new jsPDF('p','pt','letter'),W=doc.internal.pageSize.getWidth(),H=doc.internal.pageSize.getHeight(),L=48,R=48;let y=42;
  const header=first=>{doc.setFillColor(11,47,89);doc.rect(0,0,W,8,'F');doc.setFont('helvetica','bold');doc.setFontSize(18);doc.setTextColor(11,47,89);doc.text('B & L Neeley, Inc.',L,34);doc.setFont('helvetica','normal');doc.setFontSize(8.5);doc.setTextColor(88,99,111);doc.text('WATER TECHNOLOGIES  •  CLEANING COMPOUNDS  •  PROCESS SOLUTIONS',L,49);doc.setDrawColor(215,224,233);doc.line(L,59,W-R,59);y=78;if(first){doc.setFont('helvetica','bold');doc.setFontSize(16);doc.setTextColor(23,34,48);doc.text('SERVICE REPORT',L,y);y+=20;doc.setFont('helvetica','normal');doc.setFontSize(9);doc.setTextColor(95,105,115);doc.text('Water, Boiler & Cooling Systems',L,y);y+=16}};
  const newPage=()=>{doc.addPage();header(false)},ensure=n=>{if(y+n>H-62)newPage()};
  header(true);
  doc.autoTable({startY:y,margin:{left:L,right:R},theme:'plain',body:[['Customer',c.name,'Facility',f.name],['Service Technician',payload.technician||'—','Date',payload.date],['Program Status',payload.program_status,'Report #',String(r.report_number)]],styles:{fontSize:9,cellPadding:5,textColor:[35,45,55]},columnStyles:{0:{fontStyle:'bold',textColor:[11,47,89],cellWidth:92},1:{cellWidth:158},2:{fontStyle:'bold',textColor:[11,47,89],cellWidth:80}}});y=doc.lastAutoTable.finalY+15;
  const m=reportMetrics(payload);doc.setFont('helvetica','bold');doc.setFontSize(11);doc.setTextColor(11,47,89);doc.text('Program Snapshot',L,y);y+=8;
  doc.autoTable({startY:y,margin:{left:L,right:R},theme:'grid',head:[['Points Tested','In Range','Slightly Out','Out of Range']],body:[[m.tested,m.green,m.yellow,m.red]],headStyles:{fillColor:[11,47,89],textColor:255,halign:'center',fontSize:8},bodyStyles:{halign:'center',fontStyle:'bold',fontSize:11,cellPadding:7},styles:{lineColor:[222,229,236],lineWidth:.5}});y=doc.lastAutoTable.finalY+18;
  payload.systems.forEach(sys=>{const rows=sys.readings.filter(x=>x.value!=='').map(x=>[x.parameter[0],x.value,x.parameter[2]==='none'?'—':target(x.parameter),statusText(x.status)]);if(!rows.length&&!sys.notes)return;ensure(88);doc.setFillColor(11,47,89);doc.roundedRect(L,y,W-L-R,24,4,4,'F');doc.setFont('helvetica','bold');doc.setFontSize(10.5);doc.setTextColor(255);doc.text(sys.equipment.name,L+10,y+16);y+=30;
    if(rows.length){const used=sys.readings.filter(x=>x.value!=='');doc.autoTable({startY:y,margin:{left:L,right:R},theme:'grid',head:[['Parameter','Result','Target','Status']],body:rows,headStyles:{fillColor:[233,239,245],textColor:[11,47,89],fontStyle:'bold',fontSize:8},styles:{fontSize:8.5,cellPadding:5,lineColor:[222,229,236],lineWidth:.5},didParseCell:d=>{if(d.section==='body'&&(d.column.index===1||d.column.index===3)){const s=used[d.row.index].status;d.cell.styles.fillColor=s==='green'?[212,237,218]:s==='yellow'?[255,243,205]:s==='red'?[248,215,218]:[255,255,255]}}});y=doc.lastAutoTable.finalY+9}
    if(sys.notes){ensure(34);doc.setFont('helvetica','bold');doc.setFontSize(8.5);doc.setTextColor(11,47,89);doc.text('Notes',L,y);y+=11;doc.setFont('helvetica','normal');doc.setTextColor(45,55,65);const lines=doc.splitTextToSize(sys.notes,W-L-R);doc.text(lines,L,y);y+=lines.length*10+7}y+=8});
  if(payload.summary){ensure(58);doc.setFont('helvetica','bold');doc.setFontSize(11);doc.setTextColor(11,47,89);doc.text('Summary & Recommendations',L,y);y+=14;doc.setFont('helvetica','normal');doc.setFontSize(9);doc.setTextColor(35,45,55);doc.text(doc.splitTextToSize(payload.summary,W-L-R),L,y)}
  const pages=doc.getNumberOfPages();for(let i=1;i<=pages;i++){doc.setPage(i);doc.setDrawColor(220,226,232);doc.line(L,H-37,W-R,H-37);doc.setFont('helvetica','normal');doc.setFontSize(7.2);doc.setTextColor(110,118,127);doc.text('B & L Neeley, Inc. • Water Technologies & Cleaning Compounds • 209-823-3571 • www.blneeley.com',L,H-22);doc.text(`Page ${i} of ${pages}`,W-R,H-22,{align:'right'})}
  const safe=s=>String(s).replace(/[^a-z0-9]+/gi,'_').replace(/^_+|_+$/g,'');doc.save(`${safe(c.name)}_${safe(f.name)}_Report_${r.service_date}.pdf`)
}
function go(id){$$('.route').forEach(x=>x.classList.remove('active'));$('#'+id).classList.add('active');$$('.nav').forEach(x=>x.classList.toggle('active',x.dataset.route===id));const names={'dashboard':['Dashboard','Service program overview'],'customers':['Customers','Customer and facility management'],'reports':['Service Reports','History, revisions, PDFs, and exports'],'new-report':['New Service Report','Field service entry'],'facility':['Facility Setup','Equipment, targets, reports, and trends']};$('#pageTitle').textContent=names[id][0];$('#pageSubtitle').textContent=names[id][1];scrollTo({top:0,behavior:'smooth'})}
function openModal(title,body){$('#modalTitle').textContent=title;$('#modalBody').innerHTML=body;$('#modal').classList.remove('hidden')}function closeModal(){$('#modal').classList.add('hidden')}function toast(s){$('#toast').textContent=s;$('#toast').classList.remove('hidden');setTimeout(()=>$('#toast').classList.add('hidden'),2500)}
function addEquipment(fromReport=false){const fid=fromReport?$('#reportFacility').value:state.facilityId;openModal('Add Equipment',`<div class="formgrid"><label>Equipment Type<select id="mType">${Object.entries(types).map(([v,n])=>`<option value="${v}">${n}</option>`).join('')}</select></label><label>Name / Tag<input id="mName" placeholder="e.g. Rental Boiler #2"></label><label>Equipment Class<select id="mClass"><option value="permanent">Permanent</option><option value="rental">Rental</option><option value="temporary">Temporary</option></select></label></div><div class="modalactions"><button class="btn" id="cancel">Cancel</button><button class="btn primary" id="saveEq">Add Equipment</button></div>`);$('#cancel').onclick=closeModal;$('#saveEq').onclick=async()=>{const n=$('#mName').value.trim();if(!n)return toast('Enter an equipment name.');if(DEMO){state.equipment.push(eq('e'+Date.now(),fid,$('#mType').value,n,$('#mClass').value));closeModal();renderFacility();if(fromReport)buildReport();toast('Equipment added.');return}try{const t=await sb.from('service_equipment_types').select('id').eq('code',$('#mType').value).single();if(t.error)throw t.error;const ins=await sb.from('service_facility_equipment').insert({facility_id:fid,equipment_type_id:t.data.id,name:n,equipment_class:$('#mClass').value,status:'active'});if(ins.error)throw ins.error;closeModal();toast('Equipment added.');await loadSupabase()}catch(e){toast(e.message)}}}
async function loadSupabase(){if(DEMO)return;const[c,f,e,r]=await Promise.all([sb.from('service_customers').select('*'),sb.from('service_facilities').select('*'),sb.from('service_facility_equipment').select('*,service_equipment_types(code,display_name)'),sb.from('service_reports').select('*').order('service_date',{ascending:false})]);if(c.error||f.error||e.error||r.error)return toast('Could not load Supabase data.');state.customers=c.data;state.facilities=f.data;state.equipment=e.data.map(x=>({id:x.id,facility_id:x.facility_id,type:x.service_equipment_types?.code||'other',name:x.name,equipment_class:x.equipment_class,status:x.status}));state.reports=r.data;state.facilityId=state.facilities[0]?.id;render()}
$$('[data-route]').forEach(x=>x.onclick=()=>go(x.dataset.route));$$('.tab').forEach(x=>x.onclick=()=>{$$('.tab').forEach(t=>t.classList.remove('active'));$$('.tabpane').forEach(t=>t.classList.remove('active'));x.classList.add('active');$('#'+x.dataset.tab).classList.add('active')});$('#customerSearch').oninput=renderCustomers;$('#reportCustomer').onchange=populateFacilities;$('#reportFacility').onchange=buildReport;$('#addEquipment').onclick=()=>addEquipment(false);$('#addEquipmentReport').onclick=()=>addEquipment(true);$('#closeModal').onclick=closeModal;$('#saveDraft').onclick=()=>saveReport('draft');$('#completeReport').onclick=()=>saveReport('completed');$('#addCustomer').onclick=()=>toast('Customer creation form is next in the admin pass.');$('#serviceDate').value=new Date().toISOString().slice(0,10);
if(DEMO)render();else loadSupabase();
})();
